import { Discipline, Material, Testimonial, FAQ, Banner, SystemSettings } from './types';

export const defaultSettings: SystemSettings = {
  purchaseUrl: "https://drive.google.com/file/d/12gIaqN6GWkFnTgrDRqN1I026UIbHYbB7/view",
  whatsappNumber: "5511999999999",
  whatsappMessage: "Olá! Gostaria de tirar algumas dúvidas sobre as apostilas de planejamento de aula para professores.",
  contactEmail: "suporte@apostilasdoprofessor.com.br",
  supportHours: "Segunda a Sexta, das 8h às 18h",
  facebookUrl: "https://facebook.com/apostilasdoprofessor",
  instagramUrl: "https://instagram.com/apostilasdoprofessor",
  youtubeUrl: "https://youtube.com/apostilasdoprofessor",
  teachersCount: 10480,
  materialsCount: 284,
  downloadsCount: 82450,
  satisfactionRate: 98,
};

export const defaultBanners: Banner[] = [
  {
    id: "banner-1",
    title: "Economize Horas Preparando Suas Aulas",
    subtitle: "Tenha acesso imediato a materiais pedagógicos completos, organizados por disciplina e prontos para usar em sala de aula.",
    badge: "⚡ ACESSO IMEDIATO & 100% EDITÁVEL NO WORD",
    ctaText: "Ver Disciplinas",
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80",
  }
];

export const defaultDisciplines: Discipline[] = [
  {
    id: "geo",
    name: "Geografia",
    emoji: "🌍",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    iconBg: "bg-teal-500",
    textColor: "text-teal-800",
    accentColor: "bg-teal-600",
    iconName: "Globe",
    description: "Planejamentos de Geografia do 6º ao 9º ano e Ensino Médio.",
    longDescription: "Materiais completos de Geografia alinhados à BNCC para o Ensino Fundamental II (6º ao 9º ano) e Ensino Médio. Inclui planos de aula detalhados, atividades dinâmicas, avaliações com gabarito e recursos visuais focados em cartografia, relevo, geopolítica e ecologia.",
    sampleContents: [
      "Plano de Aula Anual Completo e Editável (BNCC)",
      "Caderno de Atividades Práticas sobre Climatologia e Cartografia",
      "Provas Bimestrais Objetivas e Discursivas com Gabarito",
      "Slides de Apoio em PowerPoint sobre Geopolítica Mundial",
      "Atividades Complementares de Interpretação de Mapas e Gráficos",
      "Gabarito Comentado de Todos os Exercícios"
    ],
    price: 47.00,
    originalPrice: 147.00,
    grade: "Ambos",
    image: "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "his",
    name: "História",
    emoji: "📜",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    iconBg: "bg-amber-500",
    textColor: "text-amber-800",
    accentColor: "bg-amber-600",
    iconName: "Scroll",
    description: "Planejamentos de História com foco na BNCC e ENEM.",
    longDescription: "Material completo de História cobrindo toda a grade curricular do Fundamental II e Ensino Médio. Aborda desde a Pré-História e Antiguidade Clássica até a História do Brasil e Contemporânea, com foco especial na contextualização histórica e senso crítico.",
    sampleContents: [
      "Planos de Aula Detalhados Passo a Passo",
      "Banco de Atividades de Interpretação de Fontes Históricas",
      "Mapas Mentais Ilustrados de Diversos Períodos Históricos",
      "Simulados Prontos com Questões Estilo ENEM e Vestibulares",
      "Material de Apoio em PDF e Word Totalmente Editável",
      "Roteiros para Debates em Sala de Aula com Temas Atuais"
    ],
    price: 47.00,
    originalPrice: 147.00,
    grade: "Ambos",
    image: "https://images.unsplash.com/photo-1447069387593-a5de0862481e?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "por",
    name: "Português",
    emoji: "📖",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    iconBg: "bg-indigo-500",
    textColor: "text-indigo-800",
    accentColor: "bg-indigo-600",
    iconName: "BookOpen",
    description: "Língua Portuguesa para Ensino Fundamental II e Ensino Médio.",
    longDescription: "Apostila robusta contendo todo o conteúdo gramatical, morfológico, sintático e de interpretação textual. Alinhado às diretrizes da BNCC, focado na aquisição de competências linguísticas práticas e leitura analítica.",
    sampleContents: [
      "Roteiros Didáticos de Sintaxe, Morfologia e Fonética",
      "Fichas de Interpretação e Análise Textual de Gêneros Diversos",
      "Exercícios Práticos de Análise Gramatical com Gabarito",
      "Modelos de Avaliações Diagnósticas, Formativas e Somativas",
      "Sugestões de Atividades Dinâmicas e Jogos Linguísticos",
      "Arquivos em Formato Word Prontos para Edição"
    ],
    price: 49.00,
    originalPrice: 157.00,
    grade: "Ambos",
    image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "mat",
    name: "Matemática",
    emoji: "➗",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
    iconBg: "bg-sky-500",
    textColor: "text-sky-800",
    accentColor: "bg-sky-600",
    iconName: "Hash",
    description: "Equações, funções, geometria e álgebra passo a passo.",
    longDescription: "Recursos didáticos de Matemática pensados para quebrar a barreira da dificuldade da matéria. Conteúdos explicativos, listas de exercícios resolvidos, atividades contextualizadas com a vida real e roteiros de resolução de problemas.",
    sampleContents: [
      "Planejamento Semanal Alinhado às Habilidades da BNCC",
      "Listas de Exercícios Nivelados (Básico, Intermediário e Avançado)",
      "Caderno de Geometria Prática e Resolução de Problemas",
      "Avaliações com Gabarito Passo a Passo para Facilitar a Correção",
      "Modelos de Jogos Matemáticos e Desafios de Raciocínio Lógico",
      "Gabaritos Completamente Comentados para Autoavaliação"
    ],
    price: 49.00,
    originalPrice: 157.00,
    grade: "Ambos",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "red",
    name: "Redação",
    emoji: "✍️",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    iconBg: "bg-rose-500",
    textColor: "text-rose-800",
    accentColor: "bg-rose-600",
    iconName: "PenTool",
    description: "Métodos de escrita, redação ENEM e produção textual de alta nota.",
    longDescription: "Guia definitivo de escrita e produção de texto para professores estimularem redações excelentes de seus alunos. Estruturas prontas para redação dissertativo-argumentativa do ENEM, crônicas, artigos de opinião e cartas argumentativas.",
    sampleContents: [
      "Grade de Correção Detalhada Baseada nas Competências do ENEM",
      "Modelos Prontos de Redação Nota 1000 Desconstruídos",
      "Propostas Inéditas de Redação com Textos Motivadores Atuais",
      "Exercícios de Coesão, Coerência, Conectivos e Repertório",
      "Folhas de Redação Padronizadas e Prontas para Impressão",
      "Dicas de Planejamento de Texto e Brainstorming de Temas"
    ],
    price: 39.00,
    originalPrice: 119.00,
    grade: "Ensino Médio",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "esp",
    name: "Espanhol",
    emoji: "🇪🇸",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
    iconBg: "bg-yellow-500",
    textColor: "text-yellow-800",
    accentColor: "bg-yellow-600",
    iconName: "Languages",
    description: "Vocabulário, interpretação e gramática da língua espanhola.",
    longDescription: "Material completo focado em leitura, compreensão oral e escrita, vocabulário cotidiano, conjugação verbal e falsos amigos da língua espanhola. Perfeito para prender a atenção das turmas e contextualizar o idioma latino.",
    sampleContents: [
      "Planos de Aula de Conversação e Vocabulário Prático",
      "Caderno de Atividades de Interpretação de Textos em Espanhol",
      "Aulas Focadas em Cultura Hispânica e Músicas Tradicionais",
      "Exercícios de Gramática (Verbos, Preposições e Pronomes)",
      "Provas Bimestrais Completas com Gabarito Incluído",
      "Listas de Expressões Idiomáticas Mais Comuns"
    ],
    price: 37.00,
    originalPrice: 97.00,
    grade: "Ambos",
    image: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "fil",
    name: "Filosofia",
    emoji: "💭",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    iconBg: "bg-purple-500",
    textColor: "text-purple-800",
    accentColor: "bg-purple-600",
    iconName: "BrainCircuit",
    description: "História da filosofia antiga, medieval, moderna e debates éticos.",
    longDescription: "Apostila com linguagem acessível e instigante para o ensino de Filosofia. Contempla desde os pré-socráticos até as correntes filosóficas contemporâneas, com muitas sugestões de debates, seminários e análises críticas.",
    sampleContents: [
      "Fichas Didáticas sobre os Maiores Filósofos da História",
      "Roteiros Detalhados de Debates sobre Ética, Moral e Política",
      "Banco de Questões Estilo ENEM e Grandes Vestibulares",
      "Textos Clássicos Comentados e Facilitados para Alunos",
      "Atividades Criativas de Associação Teoria-Prática Cotidiana",
      "Slides Didáticos Explicativos Prontos para Uso"
    ],
    price: 39.00,
    originalPrice: 127.00,
    grade: "Ensino Médio",
    image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "soc",
    name: "Sociologia",
    emoji: "👥",
    bgColor: "bg-fuchsia-50",
    borderColor: "border-fuchsia-200",
    iconBg: "bg-fuchsia-500",
    textColor: "text-fuchsia-800",
    accentColor: "bg-fuchsia-600",
    iconName: "Users",
    description: "Análise social, cultura, cidadania e movimentos contemporâneos.",
    longDescription: "Materiais teóricos e práticos de Sociologia estruturados para debater dinâmicas sociais atuais, cidadania, desigualdades sociais, trabalho e globalização, conectando as teorias clássicas de Marx, Weber e Durkheim com o mundo atual.",
    sampleContents: [
      "Planejamento de Sociologia Totalmente Alinhado à BNCC",
      "Caderno de Atividades sobre Desigualdades Sociais e Cultura",
      "Roteiros de Pesquisa de Campo Social para Estudantes",
      "Provas Dissertativas Prontas com Roteiro de Correção",
      "Textos de Apoio e Artigos Atuais para Análise e Debate",
      "Mapas Conceituais das Principais Teorias Sociológicas"
    ],
    price: 39.00,
    originalPrice: 127.00,
    grade: "Ensino Médio",
    image: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "bio",
    name: "Biologia",
    emoji: "🌿",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    iconBg: "bg-green-500",
    textColor: "text-green-800",
    accentColor: "bg-green-600",
    iconName: "Leaf",
    description: "Citologia, genética, ecologia e evolução para o Ensino Médio.",
    longDescription: "Conteúdo completo de Biologia extremamente detalhado e focado nas principais exigências acadêmicas. Inclui roteiros de aulas práticas em laboratório, listas de exercícios resolvidos e esquemas visuais didáticos dos sistemas do corpo.",
    sampleContents: [
      "Planos de Aula Detalhados e Editáveis (Anual e Semanal)",
      "Infográficos de Fisiologia Humana e Citologia Prontos para Imprimir",
      "Roteiros Completos de Experimentos de Laboratório Simples",
      "Banco de Questões Resolvidas e Comentadas do ENEM",
      "Exercícios Práticos de Genética e Heredogramas",
      "Slides Visuais em PowerPoint Editáveis para Suas Aulas"
    ],
    price: 49.00,
    originalPrice: 157.00,
    grade: "Ensino Médio",
    image: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cie",
    name: "Ciências",
    emoji: "🔬",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    iconBg: "bg-cyan-500",
    textColor: "text-cyan-800",
    accentColor: "bg-cyan-600",
    iconName: "FlaskConical",
    description: "Química, física e biologia do 6º ao 9º ano de forma lúdica.",
    longDescription: "Material completo de Ciências Naturais focado na investigação científica para alunos do Ensino Fundamental II. Aulas lúdicas, dinâmicas de conscientização socioambiental e introdução leve aos conceitos de física e química.",
    sampleContents: [
      "Planejamento Anual Estruturado com Códigos da BNCC",
      "Atividades Práticas e Oficinas de Reciclagem e Meio Ambiente",
      "Experiências de Ciências Fáceis para Sala de Aula Comum",
      "Avaliações Periódicas Objetivas com Gabarito Incluso",
      "Fichas Didáticas sobre Sistema Solar, Corpo Humano e Plantas",
      "Arquivos Prontos e Editáveis em Microsoft Word"
    ],
    price: 45.00,
    originalPrice: 137.00,
    grade: "Ensino Fundamental II",
    image: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "fis",
    name: "Física",
    emoji: "⚛️",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    iconBg: "bg-violet-500",
    textColor: "text-violet-800",
    accentColor: "bg-violet-600",
    iconName: "Atom",
    description: "Mecânica, termologia, óptica e eletricidade de forma descomplicada.",
    longDescription: "Apostila teórica e prática de Física voltada para o Ensino Médio. Exercícios contextualizados com o dia a dia (velocidade, calor, circuitos elétricos, ondas de rádio) para tornar o aprendizado lógico e atrativo aos jovens.",
    sampleContents: [
      "Resoluções Passo a Passo de Exercícios Complexos de Mecânica",
      "Fichas de Fórmulas e Resumos Visuais Facilitadores",
      "Roteiros para Aplicação de Simuladores de Física Virtuais",
      "Banco de Avaliações com Questões de Vestibulares Tradicionais",
      "Exercícios sobre Óptica, Termodinâmica e Ondulatória",
      "Slides de Apoio Organizados por Eixo Temático"
    ],
    price: 47.00,
    originalPrice: 147.00,
    grade: "Ensino Médio",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "qui",
    name: "Química",
    emoji: "🧪",
    bgColor: "bg-lime-50",
    borderColor: "border-lime-200",
    iconBg: "bg-lime-500",
    textColor: "text-lime-800",
    accentColor: "bg-lime-600",
    iconName: "Beaker",
    description: "Tabela periódica, ligações químicas e reações em geral.",
    longDescription: "Apostilas de Química para o Ensino Médio com foco em facilitar a visualização de átomos, moléculas, reações orgânicas, estequiometria e soluções químicas. Material moderno com metodologia ativa de aprendizagem.",
    sampleContents: [
      "Tabela Periódica Interativa e Fichas de Estudo de Elementos",
      "Listas de Exercícios Resolvidos de Estequiometria e Funções Orgânicas",
      "Roteiros Práticos para Criação de Modelos de Moléculas 3D",
      "Avaliações Bimestrais Completas com Gabarito Explicativo",
      "Roteiros Explicativos de Experiências Químicas Seguras",
      "Material Completamente Editável em Word para Professores"
    ],
    price: 47.00,
    originalPrice: 147.00,
    grade: "Ensino Médio",
    image: "https://images.unsplash.com/photo-1532187863486-abf9d39d66e8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lit",
    name: "Literatura",
    emoji: "📚",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    iconBg: "bg-orange-500",
    textColor: "text-orange-800",
    accentColor: "bg-orange-600",
    iconName: "BookOpenCheck",
    description: "Análise literária, escolas literárias e clássicos obrigatórios.",
    longDescription: "Material enriquecedor cobrindo todas as Escolas Literárias desde o Quinhentismo até a Literatura Contemporânea. Perfeito para preparar alunos para as questões de análise de obras de grandes vestibulares (Unicamp, USP, etc).",
    sampleContents: [
      "Resumos Críticos de Livros de Leitura Obrigatória de Vestibulares",
      "Fichas sobre Barroco, Romantismo, Realismo, Modernismo e outros",
      "Exercícios Práticos de Análise de Poemas e Figuras de Linguagem",
      "Provas Prontas com Questões Discursivas e Objetivas de Literatura",
      "Sugestões de Projetos de Leitura Crítica e Teatros Escolares",
      "Arquivos Prontos para Impressão ou Edição Direta no Word"
    ],
    price: 39.00,
    originalPrice: 119.00,
    grade: "Ensino Médio",
    image: "https://images.unsplash.com/photo-1491841573190-701352e74467?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "edf",
    name: "Educação Física",
    emoji: "🏃",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    iconBg: "bg-red-500",
    textColor: "text-red-800",
    accentColor: "bg-red-600",
    iconName: "Activity",
    description: "Planos de aula práticos de esportes, saúde e jogos cooperativos.",
    longDescription: "Planejamento estruturado para as aulas teóricas e práticas de Educação Física. Focado no desenvolvimento psicomotor, promoção da saúde, introdução às regras de esportes variados e jogos lúdicos corporais.",
    sampleContents: [
      "Planejamento BNCC Anual com Foco em Práticas Corporais",
      "Fichas de Regras de Esportes Olímpicos e Coletivos",
      "Roteiros Detalhados de Aulas Teóricas sobre Nutrição e Anatomia",
      "Atividades de Gincanas, Jogos Cooperativos e de Lazer",
      "Modelos de Relatório de Avaliação e Desempenho Motor",
      "Garantia de Atualização Totalmente Editável no Word"
    ],
    price: 35.00,
    originalPrice: 97.00,
    grade: "Ambos",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "art",
    name: "Artes",
    emoji: "🎨",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    iconBg: "bg-emerald-500",
    textColor: "text-emerald-800",
    accentColor: "bg-emerald-600",
    iconName: "Palette",
    description: "História da arte, expressão visual, teatro e patrimônio cultural.",
    longDescription: "Estimule a criatividade com aulas de Artes completas. Cobre movimentos artísticos nacionais e internacionais, técnicas de pintura, escultura, fotografia e dinâmicas criativas de teatro e expressão corporal.",
    sampleContents: [
      "Caderno de Atividades Práticas de Desenho, Pintura e Colagem",
      "Histórias de Grandes Artistas Explicadas com Linguagem Visual",
      "Projetos Pedagógicos de Teatro, Música e Dança Escolar",
      "Avaliações Didáticas Baseadas nas Linguagens da Arte da BNCC",
      "Material de Apoio Digital para Exposição e Mostra Cultural",
      "100% de Praticidade em Arquivos Editáveis no Word"
    ],
    price: 35.00,
    originalPrice: 97.00,
    grade: "Ambos",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "pdv",
    name: "Projeto de Vida",
    emoji: "🎯",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    iconBg: "bg-pink-500",
    textColor: "text-pink-800",
    accentColor: "bg-pink-600",
    iconName: "Compass",
    description: "Autoconhecimento, inteligência emocional e carreira estudantil.",
    longDescription: "Aborde com maestria este componente obrigatório do Novo Ensino Médio. Materiais focados em inteligência emocional, habilidades socioemocionais, planejamento de carreira e desenvolvimento do cidadão consciente.",
    sampleContents: [
      "Dinâmicas de Grupo de Autoconhecimento e Empatia",
      "Roteiros Práticos de Planejamento de Metas a Curto e Longo Prazo",
      "Aulas Exclusivas sobre Orientação Vocacional e Trabalho",
      "Caderno de Atividades de Educação Financeira e Economia Prática",
      "Provas Formativas Baseadas na Autoavaliação do Estudante",
      "Guia do Professor Editável no Word com Dicas de Mediação"
    ],
    price: 39.00,
    originalPrice: 129.00,
    grade: "Ensino Médio",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80"
  }
];

export const defaultMaterials: Material[] = [
  {
    id: "mat-1",
    title: "Combo Completo de Geografia (EF II + EM)",
    disciplineId: "geo",
    disciplineName: "Geografia",
    price: 47.00,
    originalPrice: 147.00,
    rating: 4.9,
    reviewsCount: 184,
    isBestSeller: true,
    isNew: false,
    image: "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=600&q=80",
    description: "Todos os planos de aula de cartografia, biomas, recursos hídricos e geopolítica com atividades resolvidas de acordo com a BNCC.",
    pages: 340,
    fileFormat: "Word (.docx) 100% Editável"
  },
  {
    id: "mat-2",
    title: "Apostila Completa Língua Portuguesa 6º ao 9º Ano",
    disciplineId: "por",
    disciplineName: "Português",
    price: 49.00,
    originalPrice: 157.00,
    rating: 4.8,
    reviewsCount: 224,
    isBestSeller: true,
    isNew: false,
    image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80",
    description: "Mais de 150 planos de aula detalhados e centenas de questões de análise morfossintática e de gêneros textuais.",
    pages: 480,
    fileFormat: "Word (.docx) 100% Editável"
  },
  {
    id: "mat-3",
    title: "Kit Redação Nota 1000 - Práticas e Propostas",
    disciplineId: "red",
    disciplineName: "Redação",
    price: 39.00,
    originalPrice: 119.00,
    rating: 4.95,
    reviewsCount: 312,
    isBestSeller: true,
    isNew: true,
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=600&q=80",
    description: "Passo a passo, repertório coringa, redações exemplares detalhadas e 30 temas inéditos com textos de apoio.",
    pages: 220,
    fileFormat: "PDF + Word (.docx)"
  },
  {
    id: "mat-4",
    title: "Apostila de Matemática Ensino Médio Integrado",
    disciplineId: "mat",
    disciplineName: "Matemática",
    price: 49.00,
    originalPrice: 157.00,
    rating: 4.7,
    reviewsCount: 145,
    isBestSeller: false,
    isNew: false,
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80",
    description: "Abordagem teórica e exercícios práticos de funções de 1º e 2º grau, trigonometria, geometria analítica e estatística.",
    pages: 410,
    fileFormat: "Word (.docx) 100% Editável"
  },
  {
    id: "mat-5",
    title: "Kit Ciências Investigativas EF II (6º ao 9º)",
    disciplineId: "cie",
    disciplineName: "Ciências",
    price: 45.00,
    originalPrice: 137.00,
    rating: 4.9,
    reviewsCount: 168,
    isBestSeller: false,
    isNew: false,
    image: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=600&q=80",
    description: "Excelente banco de experimentos práticos e planos de aula estruturados cobrindo ecologia, corpo humano, física e química básica.",
    pages: 310,
    fileFormat: "Word (.docx) 100% Editável"
  },
  {
    id: "mat-6",
    title: "Super Combo de Biologia Completo - Ensino Médio",
    disciplineId: "bio",
    disciplineName: "Biologia",
    price: 49.00,
    originalPrice: 157.00,
    rating: 4.92,
    reviewsCount: 198,
    isBestSeller: true,
    isNew: false,
    image: "https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?auto=format&fit=crop&w=600&q=80",
    description: "Plano anual completo com infográficos coloridos de citologia, genética, sistemas orgânicos e ecologia para o EM.",
    pages: 450,
    fileFormat: "PDF + Word (.docx)"
  },
  {
    id: "mat-7",
    title: "Projeto de Vida - Práticas para o Ensino Médio",
    disciplineId: "pdv",
    disciplineName: "Projeto de Vida",
    price: 39.00,
    originalPrice: 129.00,
    rating: 4.88,
    reviewsCount: 124,
    isBestSeller: false,
    isNew: true,
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80",
    description: "Dinâmicas de inteligência emocional, elaboração de currículos, postura profissional e autoconhecimento.",
    pages: 180,
    fileFormat: "Word (.docx) 100% Editável"
  },
  {
    id: "mat-8",
    title: "Apostila de Filosofia e Sociologia para o Novo Ensino Médio",
    disciplineId: "fil",
    disciplineName: "Filosofia",
    price: 57.00,
    originalPrice: 187.00,
    rating: 4.91,
    reviewsCount: 156,
    isBestSeller: false,
    isNew: false,
    image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=600&q=80",
    description: "Kit integrado contendo planos de debates, mapas mentais explicativos dos maiores pensadores e simulados prontos.",
    pages: 350,
    fileFormat: "Word (.docx) 100% Editável"
  }
];

export const defaultTestimonials: Testimonial[] = [
  {
    id: "t-1",
    name: "Dra. Eliane Souza",
    role: "Professora de História do Ensino Médio",
    city: "Porto Alegre",
    state: "RS",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&h=150&q=80",
    comment: "Estou simplesmente encantada com o material de História. Poupei dezenas de horas de trabalho e ganhei finais de semana inteiros com a minha família. As atividades estimulam o pensamento crítico e as avaliações vêm perfeitamente alinhadas à BNCC. Recomendo fortemente a todos os meus colegas docentes!",
    verifiedPurchase: true
  },
  {
    id: "t-2",
    name: "Prof. Marcos Vinícius",
    role: "Professor de Matemática do 8º e 9º Ano",
    city: "Belo Horizonte",
    state: "MG",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&h=150&q=80",
    comment: "Dar aulas de matemática para adolescentes é sempre um desafio. Os exercícios contextualizados do kit trouxeram um engajamento que eu nunca tinha conseguido antes. Meus alunos adoram os problemas estruturados que simulam situações reais do cotidiano.",
    verifiedPurchase: true
  },
  {
    id: "t-3",
    name: "Professora Aline Santos",
    role: "Professora de Redação e Literatura",
    city: "Campinas",
    state: "SP",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&h=150&q=80",
    comment: "O material de Redação é fantástico! As propostas de redação com os textos motivadores bem organizados facilitam muito o trabalho. Os alunos adoraram a desconstrução das redações Nota 1000 que vêm no kit.",
    verifiedPurchase: true
  },
  {
    id: "t-4",
    name: "Profa. Cláudia Rodrigues",
    role: "Professora de Geografia e Sociologia",
    city: "Salvador",
    state: "BA",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=150&h=150&q=80",
    comment: "Excelente qualidade didática. Os mapas conceituais e os roteiros de debates de sociologia ajudaram muito a dinamizar o ensino. O melhor é poder editar tudo no Word, permitindo colocar o timbre da escola e ajustar os tópicos perfeitamente.",
    verifiedPurchase: true
  },
  {
    id: "t-5",
    name: "Prof. Thiago Oliveira",
    role: "Professor de Física e Química",
    city: "Rio de Janeiro",
    state: "RJ",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&h=150&q=80",
    comment: "Eu tinha muita dificuldade em bolar relatórios e provas de recuperação criativas. O banco de avaliações que acompanha os materiais de exatas é extremamente rico e poupa um tempo precioso de digitação e formatação.",
    verifiedPurchase: true
  },
  {
    id: "t-6",
    name: "Profa. Letícia Marcondes",
    role: "Professora de Biologia",
    city: "Curitiba",
    state: "PR",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&h=150&q=80",
    comment: "Excelente suporte! O acesso às apostilas foi disponibilizado no meu e-mail instantaneamente após o Pix. Tive uma dúvida na abertura de uma pasta de biologia e eles me responderam no WhatsApp em menos de 5 minutos. Muito profissionais!",
    verifiedPurchase: true
  },
  {
    id: "t-7",
    name: "Prof. Ricardo Mendes",
    role: "Coordenador Pedagógico",
    city: "Goiânia",
    state: "GO",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&h=150&q=80",
    comment: "Comprei vários pacotes de disciplinas para disponibilizar para o corpo docente da nossa escola particular. A equipe de professores está maravilhada com a facilidade e qualidade de conteúdo. Recomendo o investimento!",
    verifiedPurchase: true
  },
  {
    id: "t-8",
    name: "Profa. Patrícia Lima",
    role: "Professora de Projeto de Vida e Artes",
    city: "Recife",
    state: "PE",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&h=150&q=80",
    comment: "Os planos para Projeto de Vida são extremamente modernos, trabalham muito bem a empatia e o futuro profissional dos adolescentes. Os materiais de Artes também contam com roteiros muito interativos de pintura e colagem.",
    verifiedPurchase: true
  }
];

export const defaultFaqs: FAQ[] = [
  {
    id: "faq-1",
    question: "Como recebo o material?",
    answer: "Você receberá o acesso imediatamente em seu e-mail cadastrado logo após a confirmação do pagamento. O link direciona para pastas organizadas de onde você poderá baixar todas as apostilas de planejamento de uma só vez ou por disciplina."
  },
  {
    id: "faq-2",
    question: "Recebo imediatamente?",
    answer: "Sim! Pagamentos realizados via Pix ou Cartão de Crédito são aprovados instantaneamente e o sistema envia o e-mail de acesso na mesma hora. Pagamentos realizados por boleto bancário podem levar de 1 a 2 dias úteis para compensação."
  },
  {
    id: "faq-3",
    question: "Posso imprimir?",
    answer: "Sim, com certeza! Todos os materiais estão diagramados em formato A4 padrão, em excelente resolução de imagem, perfeitamente formatados para impressão em impressoras caseiras ou em gráficas."
  },
  {
    id: "faq-4",
    question: "Funciona no celular?",
    answer: "Sim! Os arquivos podem ser abertos, baixados e visualizados perfeitamente em qualquer dispositivo móvel (Android ou iOS), além de computadores e tablets. Para as edições de arquivos Word, basta utilizar o aplicativo Word ou Google Documentos do celular."
  },
  {
    id: "faq-5",
    question: "Os arquivos são PDF?",
    answer: "Nossos materiais são distribuídos em ambos os formatos: PDF pronto para impressão de altíssima qualidade e, mais importante, em arquivos Microsoft Word (.docx) 100% editáveis para que você consiga modificar cabeçalhos, questões ou o que desejar."
  },
  {
    id: "faq-6",
    question: "Posso acessar quantas vezes quiser?",
    answer: "Sim! O acesso aos links de download é permanente e vitalício. Você poderá fazer o download dos materiais em seu computador ou celular e usá-los quantas vezes quiser ao longo da sua jornada docente."
  },
  {
    id: "faq-7",
    question: "Existe garantia?",
    answer: "Oferecemos uma garantia incondicional de 7 dias de satisfação. Se por qualquer motivo você julgar que as apostilas não são ideais para a sua rotina, devolvemos 100% do seu dinheiro, sem questionamentos. O seu risco é zero!"
  }
];
